apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${{ values.name }}-dev
resources:
  - ../../base
images:
  - name: harbor.10.0.0.200.nip.io/library/${{ values.name }}
    newTag: "latest"
patches:
  - path: patch-resources.yaml
