app:
  title: minicloud platform
  baseUrl: https://backstage.10.0.0.200.nip.io

organization:
  name: andrelair-platform

backend:
  baseUrl: https://backstage.10.0.0.200.nip.io
  listen: ':7007'
  cors:
    origin: https://backstage.10.0.0.200.nip.io
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  reading:
    allow:
      - host: raw.githubusercontent.com
      - host: github.com
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

auth:
  environment: production
  providers:
    oidc:
      production:
        metadataUrl: https://auth.10.0.0.200.nip.io/application/o/backstage/.well-known/openid-configuration
        clientId: ${AUTH_OIDC_CLIENT_ID}
        clientSecret: ${AUTH_OIDC_CLIENT_SECRET}
        callbackUrl: https://backstage.10.0.0.200.nip.io/api/auth/oidc/handler/frame
        scope: 'openid profile email'
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityProfileEmail
            - resolver: emailLocalPartMatchingUserEntityName

catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, User, Group]
  locations:
    - type: url
      target: https://raw.githubusercontent.com/andrelair-platform/minicloud-platform-docs/main/catalog-info.yaml
    - type: url
      target: https://raw.githubusercontent.com/andrelair-platform/minicloud-ansible/main/catalog-info.yaml
    - type: url
      target: https://raw.githubusercontent.com/andrelair-platform/minicloud-opentofu/main/catalog-info.yaml
    - type: url
      target: https://raw.githubusercontent.com/andrelair-platform/minicloud-gitops/main/catalog-info.yaml
    - type: url
      target: https://raw.githubusercontent.com/andrelair-platform/platform-demo/main/catalog-info.yaml
    - type: url
      target: https://raw.githubusercontent.com/andrelair-platform/minicloud-backstage/main/catalog-info.yaml

kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - name: minicloud
          url: https://10.0.0.2:6443
          authProvider: 'serviceAccount'
          serviceAccountToken: ${K8S_SA_TOKEN}
          caData: ${K8S_CA_DATA}
          skipTLSVerify: false
          skipMetricsLookup: false

argocd:
  username: ${ARGOCD_USERNAME}
  password: ${ARGOCD_PASSWORD}
  appLocatorMethods:
    - type: 'config'
      instances:
        - name: minicloud
          url: https://argocd.10.0.0.200.nip.io

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'
