apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: andrelair-platform/${{ values.name }}
    backstage.io/kubernetes-id: ${{ values.name }}
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: ${{ values.name }}-dev
  links:
    - url: https://argocd.devandre.sbs/applications/${{ values.name }}-dev
      title: ArgoCD
      icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: minicloud-platform
